### ISSUE TITLE
Disable idling for nominated functions

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/faas-idler#10]
Idling is not appropriate for all functions, so we need to come up with a way for functions to opt-out or opt-in.

We need to avoid making breaking changes and currently have several other documented labels used for tuning auto-scaling.

```
com.openfaas.scale.min By default this is set to 1
com.openfaas.scale.max The current default value is 20 for 20 replicas
com.openfaas.scale.factor By default this is set to 20% and has to be a value between 0-100 (including borders)
```

It is important to retain the min/max values for their existing semantics for our existing users, this is why I have not set `com.openfaas.scale.min` to `0` since it's valid to want a minimum availability and the ability to scale to zero.

We should pick *one* option - either opt-in or opt-out. Here are some examples of how it could look:

* Opt-in:

No functions are idled unless opted-in.

```
labels:
  com.openfaas.scale.min: 5
  com.openfaas.scale.max: 15

# Then adding one of these depending on what name we prefer:
  com.openfaas.scale.zero: true
  com.openfaas.scale.idling: true
```

* Opt-out:

All functions are idled unless an additional label is given:

```
labels:
  com.openfaas.scale.min: 5
  com.openfaas.scale.max: 15

# Then adding one of these depending on what name we prefer:
  com.openfaas.scale.zero: false
  com.openfaas.scale.idling: false
```
