### ISSUE TITLE
idler logs: invalid character 'E' looking for beginning of value

### ISSUE THREAD

**Issue by philwinder** [openfaas-incubator/faas-idler#27]
Hi all.

When adding the `com.openfaas.scale.zero: true` label to a k8s manifest it causes an error in the logs. No scaling is performed.

## Possible Solution
Not sure, but it looks like some kind of encoding error.

## Steps to Reproduce (for bugs)

Just the default install + the operator. The operator is required for the CRDs.

```
helm repo add openfaas https://openfaas.github.io/faas-netes/
helm repo update
helm fetch openfaas/openfaas --untar
helm template openfaas \
    --namespace openfaas  \
    --set basic_auth=true \
    --set functionNamespace=openfaas-fn \
    --set operator.create=true \
    > templated.yaml
```

```
PASSWORD=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)
echo $PASSWORD

kubectl apply -f namespace.yaml

kubectl -n openfaas create secret generic basic-auth \
--from-literal=basic-auth-user=admin \
--from-literal=basic-auth-password="$PASSWORD"

kubectl apply -f templated.yaml
```

```
kubectl -n openfaas-fn apply -f https://raw.githubusercontent.com/openfaas-incubator/openfaas-operator/master/artifacts/nodeinfo.yaml
```

This works ok. Logs are normal.

Now edit the nodeinfo yaml and add the `label` `com.openfaas.scale.zero: true`. E.g.

```yaml
...
spec:
  name: nodeinfo
  handler: node main.js
  image: functions/nodeinfo
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "15"
    com.openfaas.scale.zero: true
...
```

And check the logs of the idler. You will see `invalid character 'E' looking for beginning of value`

## Your Environment
Kubernetes with helm chart with the operator.

## Error Logs

```
$ kubectl -n openfaas logs faas-idler-7f55df8784-vmk6s -f
dry_run: true
gateway_url: http://gateway.openfaas:8080/
2019/07/09 08:28:19 Gateway version: 0.14.4, SHA: ced4ee56dc003cf4f3baa0954ab692f4be54f57b
inactivity_duration: 15m0s {{200 nodeinfo} [1.56266089902e+09 0]}
2019/07/09 08:28:19 Skip: nodeinfo due to missing label

2019/07/09 08:29:19 invalid character 'E' looking for beginning of value

2019/07/09 08:30:19 invalid character 'E' looking for beginning of value

2019/07/09 08:31:19 invalid character 'E' looking for beginning of value

2019/07/09 08:32:19 invalid character 'E' looking for beginning of value
```

Note that on the first reconcilation it skipped, because the nodeinfo manifest did not have the  `com.openfaas.scale.zero: true` label.

**Comment by alexellis** [comment]
Can you get the logs of the components in the openfaas namespace please?

**Comment by alexellis** [comment]
I'm using this with faas-netes (non CRD controller) in OpenFaaS Cloud live. There looks to be a problem, but if you want to get moving on this switching should work.

**Comment by alexellis** [comment]
This is what I'm trying:

```
helm repo update  && helm upgrade openfaas --install openfaas/openfaas     --namespace openfaas      --set basic_auth=true     --set functionNamespace=openfaas-fn --set operator.create=true --set faasIdler.dryRun=false --set faasIdler.inactivityDuration=3m

faas-cli store deploy -g 127.0.0.1:31112 nodeinfo --label com.openfaas.scale.zero=true

echo -n verbose | faas-cli invoke -g 127.0.0.1:31112 nodeinfo
```

Then:

```
kubectl logs -n openfaas deploy/faas-idler -f

# and

kubectl logs -n openfaas deploy/gateway gateway -f
```

![Screenshot 2019-07-09 at 10 15 59](https://user-images.githubusercontent.com/6358735/60875819-91d17a80-a232-11e9-9b82-f3c1e79677d4.png)

The function was scaled down.

The gateway version looks like it was taken yesterday before pushing 0.15.0, but that shouldn't have a bearing on it.

Here is the generated CRD entry from the `store deploy` command:

```
kubectl get function/nodeinfo -n openfaas-fn -o yaml --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  generation: 1
  name: nodeinfo
  selfLink: /apis/openfaas.com/v1alpha2/namespaces/openfaas-fn/functions/nodeinfo
spec:
  annotations: {}
  constraints: []
  environment: {}
  handler: node main.js
  image: functions/nodeinfo:latest
  labels:
    com.openfaas.scale.zero: "true"
  limits: null
  name: nodeinfo
  readOnlyRootFilesystem: true
  replicas: 0
  requests: null
  secrets: []
status:
  availableReplicas: 0
```

Phil, can you think what else you may be doing differently?

**Comment by alexellis** [comment]
I've tried the default setting of `faasIdler.dryRun=true` and that also didn't reproduce an error for me.

**Comment by alexellis** [comment]
@stefanprodan made an observation about your CRD spec, which may be related. Labels need to be in key/value using strings.

```
...
spec:
  name: nodeinfo
  handler: node main.js
  image: functions/nodeinfo
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "15"
    com.openfaas.scale.zero: true
...
```

Should be:

```
...
spec:
  name: nodeinfo
  handler: node main.js
  image: functions/nodeinfo
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "15"
    com.openfaas.scale.zero: "true"
...
```
